from typing import TypedDict, Dict, List, Callable, Awaitable

# Agent state

# we need states for:
# user query
# plan generated by the LLM 
# results obtained by each search tool
# reflection
# summary

class AgentState(TypedDict):
    query: str # The user query
    original_plan: Dict[str, str] # Entire plan returned by the planner, with rationale and reflection
    plan: List[Dict] # List of plan dicts with tool name, search parameters and reasoning
    results: Dict[str, List] # Result of each search tool
    reflection: bool | None # To determine whether the findings are enough to summarize
    reflection_notes: str # LLM's reasoning notes for the reflection
    summary: str # Final summary
    relevant_docs: List[str] # Documents relevant to the user query and analysis focus
    count: int # Number of iterations of the planner -> reflection loop
    publish: Callable[[str, str, Dict | None], Awaitable[None]] # Function to put events into an async queue